apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  # DB_HOST: mysql
    DB_HOST: db-dev.devopswithaws.store
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup db-dev.devopswithaws.store; do echo waiting for myservice; sleep 2; done"]
      containers:
      - name: backend
        image: saikumar718/backend:v1.0
        resources:
           requests:
              cpu: "100m"
              memory: "125Mi"
           limits:
              cpu: "150m"
              memory: "250Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          initialDelaySeconds: 30
          periodSeconds: 5
        envFrom:
        - configMapRef:
           name: backend
---
apiVersion: v1 
kind: Service 
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
